### ISSUE TITLE
Depends: R (>= 3.6)

### ISSUE THREAD

**Issue by bitmask** [cbg-ethz/mnem#1]
The latest commit has prevented mnem from installing on current stable R 3.5.1.  Could you please revert this depends, or add a release tag to the previous commit so that it could still be installed?

**Comment by MartinFXP** [comment]
Thanks for the suggestion. I'll try to tag stable releases in the future. 'mnem' is currently under review at bioconductor and the development version requires R 3.6 or higher. However,

```r
library(devtools)
install_github("cbg-ethz/mnem", ref = "cffcdc42f500109179d1782c0ff5b2651adf1422")
```

should work with R 3.5 or higher.
